Offloaded PID working on Comp and swerve 1 bot
Team100/main2023 pull request #223
Opened 2023-08-03 01:43 UTC by Coolearthsky

2023-08-03 03:12 UTC, truher requested changes
Thanks for making this PR and giving me the opportunity to review it!  I left a few comments for you.

2023-08-03 03:12 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/FalconTurningMotor.java
> +        m_motor.config_kF(0, 0.05);
i'm confused by the setting of kF here; kF is the feedforward constant, so it's like you're just adding a small positive constant all the time. why?

2023-08-03 03:12 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/FalconTurningMotor.java
> +    public void setPID(ControlMode control, double outputRadiansPerSec) {
this should be a separate method for velocity control (see my comment in CanTurningMotor)

2023-08-03 03:12 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/NeoTurningMotor.java
> +        m_pidController.setI(1e-4);
why is I not zero here?

2023-08-03 03:12 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/NeoTurningMotor.java
what robot uses a neo turning motor?

2023-08-03 03:12 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/NeoTurningMotor.java
> +        double motorGearing = 1;
this gearing number seems suspicious.

2023-08-03 03:12 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/FalconTurningMotor.java
> +        m_motor.configNominalOutputForward(0);
are these "peak output" numbers not the defaults?

2023-08-05 02:00 UTC, Coolearthsky commented
I did make some changes

2023-08-05 15:39 UTC, truher requested changes

2023-08-05 15:39 UTC, truher commented on swerve100/src/main/java/org/team100/frc2023/subsystems/SwerveModuleFactory.java
> +                210, // kP: High P to keep the measurments acurate while maintaining an agresive wheel turning
maybe link to a doc where you show some data?  i still don't see how this isn't saturating the controller.  what's the maximum possible speed?  what's the max error you've seen?

2023-08-05 15:39 UTC, truher commented on swerve100/src/main/java/org/team100/frc2023/subsystems/SwerveModuleFactory.java
> +                10, // kS: Multiplied by around 20 of previous value as that is how much we changed P by
i'm still confused by the use of feedforward here.

2023-08-05 15:39 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/CANTurningMotor.java
> +        double ticksPerRevolution = 1024;
since there's a lot of duplicated logic between the TalonFX and TalonSRX versions of this file, maybe extract it to a "util" class of some kind?

2023-08-05 15:39 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/CANTurningMotor.java
> +    public void setPIDPosition(double outputRadians) {
does anything actually use this?  if you're not using it you can just remove it.

2023-08-05 15:39 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/NeoTurningMotor.java
> +        double motorGearing = 1;//I believe there are not any robotics that actually use a neo turning motor I was changing this class to be more ready in case we do
you shouldn't really write code in advance of needing it; if nothing uses this, then you can leave this stuff out.  just throw UnsupportedOperationException.

2023-08-05 15:39 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/FalconTurningMotor.java
> +        m_motor.configNominalOutputForward(0);
the "nominal" ones are *also* the defaults, no?

2023-08-05 15:39 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/FalconTurningMotor.java
> +        m_motor.config_kF(0, 0.05);
ah i'm wrong about this, kF is the coefficient.

https://v5.docs.ctr-electronics.com/en/stable/ch16_ClosedLoop.html#how-to-calculate-kf

is that how you came up with 0.05?  that seems to be the number for the zero-load case.  how does it perform with P/I/D zero?

2023-08-07 22:09 UTC, Coolearthsky commented on swerve100/src/main/java/org/team100/lib/motor/turning/CANTurningMotor.java
> -        if (channel == 5) {
This was for when we were using positional control, we would feed it the value from the encoder.

2023-09-01 02:50 UTC, truher requested changes
hey i took another look at this PR, i'd like it to get finished up soon, but there are still lots of unresolved issues.  maybe we could plan to finish it on saturday?

2023-09-01 02:50 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/drive/FalconDriveMotor.java
> +        double revolutionsPerSec = outputMetersPerSec*3.479750259;
i'd like to approve this PR sometimes soon.  could you explain these mystery numbers here?

2023-09-01 02:50 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/CANTurningMotor.java
> +        m_motor.config_kD(0, .25);
what do these numbers mean?  for example, 0.05 for F?  why?

2023-09-01 02:50 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/CANTurningMotor.java
> +        m_motor.set(ControlMode.Velocity, ticksPer100ms*gearRatio);
isn't this where you would have the arbitrary feedforward part too?

2023-09-01 02:50 UTC, truher commented on swerve100/src/main/java/org/team100/lib/motor/turning/FalconTurningMotor.java
> +        if (revolutionsPerSec<.25) {
this is where you'd want to use the *actual* wheel speed, not the commanded speed, right?

2023-09-10 01:42 UTC, truher approved these changes

2023-09-10 01:47 UTC, merged